name: Build and Deploy Docs
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build docs
        run: ./gradlew clean dokkaJavadoc
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: build/dokka/javadoc
