
name: Release to OSSRH
on:
  push:
    tags:
      - chrome-reactive-kotlin-*

jobs:
  test:
    name: "Test and release to Sonatype"
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Xmx8198m -XX:MaxPermSize=4096m -XX:+HeapDumpOnOutOfMemoryError"
      GRADLE_FLAGS: "--no-daemon -i"
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Tests
        run: ./gradlew clean test ${GRADLE_FLAGS}

      - name: Populate gradle.properties
        run: |
          echo -e "nexusUsername=${{ secrets.SONATYPE_USER }}" > gradle.properties
          echo -e "nexusPassword=${{ secrets.SONATYPE_PASSWORD }}" >> gradle.properties
          echo -e "githubToken=${{ secrets.ACCESS_TOKEN }}" >> gradle.properties
          echo -e "signingKey=${{ secrets.SIGNING_KEY }}" >> gradle.properties
          echo -e "signingPassword=${{ secrets.SIGNING_PASSWORD }}" >> gradle.properties

      - name: Assemble artefacts
        run: ./gradlew assemble ${GRADLE_FLAGS}

      - name: Publish to Sonatype
        run: ./gradlew publishToSonatype ${GRADLE_FLAGS}

      - name: Close and release Sonatype repository
        run: ./gradlew closeAndReleaseRepository ${GRADLE_FLAGS}
