
name: Release to OSSRH
on:
  push:
    tags:
      - chrome-reactive-kotlin-*

jobs:
  test:
    name: "Test and release"
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: Tests
        run: ./gradlew clean test
      - name: Populate gradle.properties
        run: echo -e "nexusUsername=${{ secrets.SONATYPE_USER }}\nnexusPassword=${{ secrets.SONATYPE_PASSWORD }}" > gradle.properties
      - name: Release to Sonatype OSS
        run: bash deploy/deploy.sh
        env:
           SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
           SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
