name: Tests

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    name: "Run all tests"
    runs-on: ubuntu-latest
    env:
       GRADLE_OPTS: "-Xmx8198m -XX:MaxPermSize=4096m -XX:+HeapDumpOnOutOfMemoryError"
       GRADLE_FLAGS: "--no-daemon -i"
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Run tests
      run: ./gradlew clean test ${GRADLE_FLAGS}