name: Tests

on: [push, pull_request]

jobs:
  test:
    name: "Test with gradle"
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Tests
      run: ./gradlew clean test -i