name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: "Test with gradle"
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Tests
      run: ./gradlew clean test -i