name: Update protocol to ToT

on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  update:
    name: "Update protocol via update.sh"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run headless chrome
        run: docker container run -d -p 9222:9222 zenika/alpine-chrome --no-sandbox --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 about:blank
      - name: Update protocol
        run: ./update.sh
